server:
  port: 9001
spring:
  application:
    name: enterprise-board-comment-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:33061/comment?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8&allowPublicKeyRetrieval=true&rewriteBatchedStatements=true&cachePrepStmts=true&useServerPrepStmts=true
    username: user
    password: password
    hikari:
      maximum-pool-size: 30
      minimum-idle: 10
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    open-in-view: false
    show-sql: false  # 성능 최적화를 위해 비활성화
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        # 배치 처리 설정
        jdbc:
          batch_size: 5000
          batch_versioned_data: true
          fetch_size: 1000
        # SQL 순서 최적화
        order_inserts: true
        order_updates: true
        # 통계 비활성화 (성능 향상)
        generate_statistics: false
        # 캐시 비활성화 (배치 처리에서는 불필요)
        cache:
          use_second_level_cache: false
          use_query_cache: false
        # 메타데이터 최적화
        temp:
          use_jdbc_metadata_defaults: false
